# Top-level developer tasks for the ssh-poker-game monorepo.
# Run inside the Dev Container (.devcontainer) so Go, Rust, and protoc are present.

PROTO_INCLUDE := proto/poker/v1
PROTO_FILE := proto/poker/v1/poker.proto
GO_PB_OUT := gateway/internal/pokerpb

.PHONY: help proto proto-go proto-rust build build-rust build-go test test-rust test-go lint-rust fmt-rust clean

help:
	@echo "Targets:"
	@echo "  proto        Generate gRPC code for Go and Rust"
	@echo "  build        Build Rust workspace and Go gateway"
	@echo "  test         Run Rust and Go tests"
	@echo "  lint-rust    cargo clippy -D warnings"

# --- codegen ---------------------------------------------------------------
proto: proto-rust proto-go

# Rust code is generated by engine-service/build.rs during cargo build.
proto-rust:
	cargo build -p engine-service

proto-go:
	mkdir -p $(GO_PB_OUT)
	protoc -I $(PROTO_INCLUDE) \
		--go_out=$(GO_PB_OUT) --go_opt=paths=source_relative \
		--go-grpc_out=$(GO_PB_OUT) --go-grpc_opt=paths=source_relative \
		$(PROTO_FILE)

# --- build -----------------------------------------------------------------
build: build-rust build-go

build-rust:
	cargo build --workspace

build-go: proto-go
	cd gateway && go build ./...

# --- test ------------------------------------------------------------------
test: test-rust test-go

test-rust:
	cargo test --workspace

test-go: proto-go
	cd gateway && go test ./...

# --- quality ---------------------------------------------------------------
lint-rust:
	cargo clippy --workspace --all-targets -- -D warnings

fmt-rust:
	cargo fmt

clean:
	cargo clean
	rm -rf $(GO_PB_OUT)
