// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: poker.proto

package pokerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionKind int32

const (
	ActionKind_ACTION_KIND_UNSPECIFIED ActionKind = 0
	ActionKind_ACTION_KIND_FOLD        ActionKind = 1
	ActionKind_ACTION_KIND_CHECK       ActionKind = 2
	ActionKind_ACTION_KIND_CALL        ActionKind = 3
	ActionKind_ACTION_KIND_BET         ActionKind = 4
	ActionKind_ACTION_KIND_RAISE       ActionKind = 5
	ActionKind_ACTION_KIND_ALL_IN      ActionKind = 6
)

// Enum value maps for ActionKind.
var (
	ActionKind_name = map[int32]string{
		0: "ACTION_KIND_UNSPECIFIED",
		1: "ACTION_KIND_FOLD",
		2: "ACTION_KIND_CHECK",
		3: "ACTION_KIND_CALL",
		4: "ACTION_KIND_BET",
		5: "ACTION_KIND_RAISE",
		6: "ACTION_KIND_ALL_IN",
	}
	ActionKind_value = map[string]int32{
		"ACTION_KIND_UNSPECIFIED": 0,
		"ACTION_KIND_FOLD":        1,
		"ACTION_KIND_CHECK":       2,
		"ACTION_KIND_CALL":        3,
		"ACTION_KIND_BET":         4,
		"ACTION_KIND_RAISE":       5,
		"ACTION_KIND_ALL_IN":      6,
	}
)

func (x ActionKind) Enum() *ActionKind {
	p := new(ActionKind)
	*p = x
	return p
}

func (x ActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_poker_proto_enumTypes[0].Descriptor()
}

func (ActionKind) Type() protoreflect.EnumType {
	return &file_poker_proto_enumTypes[0]
}

func (x ActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionKind.Descriptor instead.
func (ActionKind) EnumDescriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{0}
}

type Suit int32

const (
	Suit_SUIT_UNSPECIFIED Suit = 0
	Suit_SUIT_CLUBS       Suit = 1
	Suit_SUIT_DIAMONDS    Suit = 2
	Suit_SUIT_HEARTS      Suit = 3
	Suit_SUIT_SPADES      Suit = 4
)

// Enum value maps for Suit.
var (
	Suit_name = map[int32]string{
		0: "SUIT_UNSPECIFIED",
		1: "SUIT_CLUBS",
		2: "SUIT_DIAMONDS",
		3: "SUIT_HEARTS",
		4: "SUIT_SPADES",
	}
	Suit_value = map[string]int32{
		"SUIT_UNSPECIFIED": 0,
		"SUIT_CLUBS":       1,
		"SUIT_DIAMONDS":    2,
		"SUIT_HEARTS":      3,
		"SUIT_SPADES":      4,
	}
)

func (x Suit) Enum() *Suit {
	p := new(Suit)
	*p = x
	return p
}

func (x Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_poker_proto_enumTypes[1].Descriptor()
}

func (Suit) Type() protoreflect.EnumType {
	return &file_poker_proto_enumTypes[1]
}

func (x Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suit.Descriptor instead.
func (Suit) EnumDescriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{1}
}

type Rank int32

const (
	Rank_RANK_UNSPECIFIED Rank = 0
	Rank_RANK_TWO         Rank = 2
	Rank_RANK_THREE       Rank = 3
	Rank_RANK_FOUR        Rank = 4
	Rank_RANK_FIVE        Rank = 5
	Rank_RANK_SIX         Rank = 6
	Rank_RANK_SEVEN       Rank = 7
	Rank_RANK_EIGHT       Rank = 8
	Rank_RANK_NINE        Rank = 9
	Rank_RANK_TEN         Rank = 10
	Rank_RANK_JACK        Rank = 11
	Rank_RANK_QUEEN       Rank = 12
	Rank_RANK_KING        Rank = 13
	Rank_RANK_ACE         Rank = 14
)

// Enum value maps for Rank.
var (
	Rank_name = map[int32]string{
		0:  "RANK_UNSPECIFIED",
		2:  "RANK_TWO",
		3:  "RANK_THREE",
		4:  "RANK_FOUR",
		5:  "RANK_FIVE",
		6:  "RANK_SIX",
		7:  "RANK_SEVEN",
		8:  "RANK_EIGHT",
		9:  "RANK_NINE",
		10: "RANK_TEN",
		11: "RANK_JACK",
		12: "RANK_QUEEN",
		13: "RANK_KING",
		14: "RANK_ACE",
	}
	Rank_value = map[string]int32{
		"RANK_UNSPECIFIED": 0,
		"RANK_TWO":         2,
		"RANK_THREE":       3,
		"RANK_FOUR":        4,
		"RANK_FIVE":        5,
		"RANK_SIX":         6,
		"RANK_SEVEN":       7,
		"RANK_EIGHT":       8,
		"RANK_NINE":        9,
		"RANK_TEN":         10,
		"RANK_JACK":        11,
		"RANK_QUEEN":       12,
		"RANK_KING":        13,
		"RANK_ACE":         14,
	}
)

func (x Rank) Enum() *Rank {
	p := new(Rank)
	*p = x
	return p
}

func (x Rank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rank) Descriptor() protoreflect.EnumDescriptor {
	return file_poker_proto_enumTypes[2].Descriptor()
}

func (Rank) Type() protoreflect.EnumType {
	return &file_poker_proto_enumTypes[2]
}

func (x Rank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rank.Descriptor instead.
func (Rank) EnumDescriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{2}
}

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_PRE_FLOP    Phase = 1
	Phase_PHASE_FLOP        Phase = 2
	Phase_PHASE_TURN        Phase = 3
	Phase_PHASE_RIVER       Phase = 4
	Phase_PHASE_SHOWDOWN    Phase = 5
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_PRE_FLOP",
		2: "PHASE_FLOP",
		3: "PHASE_TURN",
		4: "PHASE_RIVER",
		5: "PHASE_SHOWDOWN",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_PRE_FLOP":    1,
		"PHASE_FLOP":        2,
		"PHASE_TURN":        3,
		"PHASE_RIVER":       4,
		"PHASE_SHOWDOWN":    5,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_poker_proto_enumTypes[3].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_poker_proto_enumTypes[3]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{3}
}

// GameStateBlob is the authoritative poker-engine GameState, serialized by the
// Rust engine. The Go gateway stores and round-trips this opaque blob without
// interpreting it; only the engine understands its contents.
type GameStateBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateBlob) Reset() {
	*x = GameStateBlob{}
	mi := &file_poker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateBlob) ProtoMessage() {}

func (x *GameStateBlob) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateBlob.ProtoReflect.Descriptor instead.
func (*GameStateBlob) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{0}
}

func (x *GameStateBlob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A player betting action. amount is only meaningful for BET and RAISE.
type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ActionKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=poker.v1.ActionKind" json:"kind,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_poker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_KIND_UNSPECIFIED
}

func (x *Action) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          Rank                   `protobuf:"varint,1,opt,name=rank,proto3,enum=poker.v1.Rank" json:"rank,omitempty"`
	Suit          Suit                   `protobuf:"varint,2,opt,name=suit,proto3,enum=poker.v1.Suit" json:"suit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_poker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{2}
}

func (x *Card) GetRank() Rank {
	if x != nil {
		return x.Rank
	}
	return Rank_RANK_UNSPECIFIED
}

func (x *Card) GetSuit() Suit {
	if x != nil {
		return x.Suit
	}
	return Suit_SUIT_UNSPECIFIED
}

// A single seat as seen by a particular viewer. hole_cards is populated only
// for the viewing player's own seat.
type SeatView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          uint32                 `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Chips         uint64                 `protobuf:"varint,3,opt,name=chips,proto3" json:"chips,omitempty"`
	CurrentBet    uint64                 `protobuf:"varint,4,opt,name=current_bet,json=currentBet,proto3" json:"current_bet,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // active | folded | all_in | sitting_out
	IsCurrent     bool                   `protobuf:"varint,6,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	IsDealer      bool                   `protobuf:"varint,7,opt,name=is_dealer,json=isDealer,proto3" json:"is_dealer,omitempty"`
	HoleCards     []*Card                `protobuf:"bytes,8,rep,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatView) Reset() {
	*x = SeatView{}
	mi := &file_poker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatView) ProtoMessage() {}

func (x *SeatView) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatView.ProtoReflect.Descriptor instead.
func (*SeatView) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{3}
}

func (x *SeatView) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *SeatView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SeatView) GetChips() uint64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

func (x *SeatView) GetCurrentBet() uint64 {
	if x != nil {
		return x.CurrentBet
	}
	return 0
}

func (x *SeatView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SeatView) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *SeatView) GetIsDealer() bool {
	if x != nil {
		return x.IsDealer
	}
	return false
}

func (x *SeatView) GetHoleCards() []*Card {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

// The full table rendered from one viewer's perspective.
type TableView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ViewerSeat     uint32                 `protobuf:"varint,1,opt,name=viewer_seat,json=viewerSeat,proto3" json:"viewer_seat,omitempty"`
	Phase          Phase                  `protobuf:"varint,2,opt,name=phase,proto3,enum=poker.v1.Phase" json:"phase,omitempty"`
	CommunityCards []*Card                `protobuf:"bytes,3,rep,name=community_cards,json=communityCards,proto3" json:"community_cards,omitempty"`
	Pot            uint64                 `protobuf:"varint,4,opt,name=pot,proto3" json:"pot,omitempty"`
	CurrentSeat    uint32                 `protobuf:"varint,5,opt,name=current_seat,json=currentSeat,proto3" json:"current_seat,omitempty"`
	DealerSeat     uint32                 `protobuf:"varint,6,opt,name=dealer_seat,json=dealerSeat,proto3" json:"dealer_seat,omitempty"`
	Seats          []*SeatView            `protobuf:"bytes,7,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TableView) Reset() {
	*x = TableView{}
	mi := &file_poker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableView) ProtoMessage() {}

func (x *TableView) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableView.ProtoReflect.Descriptor instead.
func (*TableView) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{4}
}

func (x *TableView) GetViewerSeat() uint32 {
	if x != nil {
		return x.ViewerSeat
	}
	return 0
}

func (x *TableView) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *TableView) GetCommunityCards() []*Card {
	if x != nil {
		return x.CommunityCards
	}
	return nil
}

func (x *TableView) GetPot() uint64 {
	if x != nil {
		return x.Pot
	}
	return 0
}

func (x *TableView) GetCurrentSeat() uint32 {
	if x != nil {
		return x.CurrentSeat
	}
	return 0
}

func (x *TableView) GetDealerSeat() uint32 {
	if x != nil {
		return x.DealerSeat
	}
	return 0
}

func (x *TableView) GetSeats() []*SeatView {
	if x != nil {
		return x.Seats
	}
	return nil
}

type PlayerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          uint32                 `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Chips         uint64                 `protobuf:"varint,3,opt,name=chips,proto3" json:"chips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerConfig) Reset() {
	*x = PlayerConfig{}
	mi := &file_poker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerConfig) ProtoMessage() {}

func (x *PlayerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerConfig.ProtoReflect.Descriptor instead.
func (*PlayerConfig) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerConfig) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerConfig) GetChips() uint64 {
	if x != nil {
		return x.Chips
	}
	return 0
}

type NewHandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Players        []*PlayerConfig        `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	SmallBlind     uint64                 `protobuf:"varint,2,opt,name=small_blind,json=smallBlind,proto3" json:"small_blind,omitempty"`
	BigBlind       uint64                 `protobuf:"varint,3,opt,name=big_blind,json=bigBlind,proto3" json:"big_blind,omitempty"`
	DealerPosition uint32                 `protobuf:"varint,4,opt,name=dealer_position,json=dealerPosition,proto3" json:"dealer_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NewHandRequest) Reset() {
	*x = NewHandRequest{}
	mi := &file_poker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHandRequest) ProtoMessage() {}

func (x *NewHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHandRequest.ProtoReflect.Descriptor instead.
func (*NewHandRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{6}
}

func (x *NewHandRequest) GetPlayers() []*PlayerConfig {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *NewHandRequest) GetSmallBlind() uint64 {
	if x != nil {
		return x.SmallBlind
	}
	return 0
}

func (x *NewHandRequest) GetBigBlind() uint64 {
	if x != nil {
		return x.BigBlind
	}
	return 0
}

func (x *NewHandRequest) GetDealerPosition() uint32 {
	if x != nil {
		return x.DealerPosition
	}
	return 0
}

// HandState carries the opaque state plus a rendered view per seat so the
// gateway can fan out without extra round-trips.
type HandState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameStateBlob         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Views         []*TableView           `protobuf:"bytes,2,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandState) Reset() {
	*x = HandState{}
	mi := &file_poker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandState) ProtoMessage() {}

func (x *HandState) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandState.ProtoReflect.Descriptor instead.
func (*HandState) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{7}
}

func (x *HandState) GetState() *GameStateBlob {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *HandState) GetViews() []*TableView {
	if x != nil {
		return x.Views
	}
	return nil
}

type ApplyActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameStateBlob         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Seat          uint32                 `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"`
	Action        *Action                `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyActionRequest) Reset() {
	*x = ApplyActionRequest{}
	mi := &file_poker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyActionRequest) ProtoMessage() {}

func (x *ApplyActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyActionRequest.ProtoReflect.Descriptor instead.
func (*ApplyActionRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyActionRequest) GetState() *GameStateBlob {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ApplyActionRequest) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *ApplyActionRequest) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type ApplyActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	State         *GameStateBlob         `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Views         []*TableView           `protobuf:"bytes,4,rep,name=views,proto3" json:"views,omitempty"`
	HandComplete  bool                   `protobuf:"varint,5,opt,name=hand_complete,json=handComplete,proto3" json:"hand_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyActionResult) Reset() {
	*x = ApplyActionResult{}
	mi := &file_poker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyActionResult) ProtoMessage() {}

func (x *ApplyActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyActionResult.ProtoReflect.Descriptor instead.
func (*ApplyActionResult) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{9}
}

func (x *ApplyActionResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ApplyActionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyActionResult) GetState() *GameStateBlob {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ApplyActionResult) GetViews() []*TableView {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *ApplyActionResult) GetHandComplete() bool {
	if x != nil {
		return x.HandComplete
	}
	return false
}

type ValidActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameStateBlob         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidActionsRequest) Reset() {
	*x = ValidActionsRequest{}
	mi := &file_poker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidActionsRequest) ProtoMessage() {}

func (x *ValidActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidActionsRequest.ProtoReflect.Descriptor instead.
func (*ValidActionsRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{10}
}

func (x *ValidActionsRequest) GetState() *GameStateBlob {
	if x != nil {
		return x.State
	}
	return nil
}

type ValidActions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          uint32                 `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Actions       []*Action              `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidActions) Reset() {
	*x = ValidActions{}
	mi := &file_poker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidActions) ProtoMessage() {}

func (x *ValidActions) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidActions.ProtoReflect.Descriptor instead.
func (*ValidActions) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{11}
}

func (x *ValidActions) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *ValidActions) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type CompleteHandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameStateBlob         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteHandRequest) Reset() {
	*x = CompleteHandRequest{}
	mi := &file_poker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteHandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteHandRequest) ProtoMessage() {}

func (x *CompleteHandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteHandRequest.ProtoReflect.Descriptor instead.
func (*CompleteHandRequest) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteHandRequest) GetState() *GameStateBlob {
	if x != nil {
		return x.State
	}
	return nil
}

type Winning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          uint32                 `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Winning) Reset() {
	*x = Winning{}
	mi := &file_poker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Winning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Winning) ProtoMessage() {}

func (x *Winning) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Winning.ProtoReflect.Descriptor instead.
func (*Winning) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{13}
}

func (x *Winning) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *Winning) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CompleteHandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *GameStateBlob         `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Winnings      []*Winning             `protobuf:"bytes,2,rep,name=winnings,proto3" json:"winnings,omitempty"`
	Views         []*TableView           `protobuf:"bytes,3,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteHandResult) Reset() {
	*x = CompleteHandResult{}
	mi := &file_poker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteHandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteHandResult) ProtoMessage() {}

func (x *CompleteHandResult) ProtoReflect() protoreflect.Message {
	mi := &file_poker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteHandResult.ProtoReflect.Descriptor instead.
func (*CompleteHandResult) Descriptor() ([]byte, []int) {
	return file_poker_proto_rawDescGZIP(), []int{14}
}

func (x *CompleteHandResult) GetState() *GameStateBlob {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *CompleteHandResult) GetWinnings() []*Winning {
	if x != nil {
		return x.Winnings
	}
	return nil
}

func (x *CompleteHandResult) GetViews() []*TableView {
	if x != nil {
		return x.Views
	}
	return nil
}

var File_poker_proto protoreflect.FileDescriptor

const file_poker_proto_rawDesc = "" +
	"\n" +
	"\vpoker.proto\x12\bpoker.v1\"#\n" +
	"\rGameStateBlob\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"J\n" +
	"\x06Action\x12(\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x14.poker.v1.ActionKindR\x04kind\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"N\n" +
	"\x04Card\x12\"\n" +
	"\x04rank\x18\x01 \x01(\x0e2\x0e.poker.v1.RankR\x04rank\x12\"\n" +
	"\x04suit\x18\x02 \x01(\x0e2\x0e.poker.v1.SuitR\x04suit\"\xec\x01\n" +
	"\bSeatView\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\rR\x04seat\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05chips\x18\x03 \x01(\x04R\x05chips\x12\x1f\n" +
	"\vcurrent_bet\x18\x04 \x01(\x04R\n" +
	"currentBet\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"is_current\x18\x06 \x01(\bR\tisCurrent\x12\x1b\n" +
	"\tis_dealer\x18\a \x01(\bR\bisDealer\x12-\n" +
	"\n" +
	"hole_cards\x18\b \x03(\v2\x0e.poker.v1.CardR\tholeCards\"\x8c\x02\n" +
	"\tTableView\x12\x1f\n" +
	"\vviewer_seat\x18\x01 \x01(\rR\n" +
	"viewerSeat\x12%\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x0f.poker.v1.PhaseR\x05phase\x127\n" +
	"\x0fcommunity_cards\x18\x03 \x03(\v2\x0e.poker.v1.CardR\x0ecommunityCards\x12\x10\n" +
	"\x03pot\x18\x04 \x01(\x04R\x03pot\x12!\n" +
	"\fcurrent_seat\x18\x05 \x01(\rR\vcurrentSeat\x12\x1f\n" +
	"\vdealer_seat\x18\x06 \x01(\rR\n" +
	"dealerSeat\x12(\n" +
	"\x05seats\x18\a \x03(\v2\x12.poker.v1.SeatViewR\x05seats\"L\n" +
	"\fPlayerConfig\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\rR\x04seat\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05chips\x18\x03 \x01(\x04R\x05chips\"\xa9\x01\n" +
	"\x0eNewHandRequest\x120\n" +
	"\aplayers\x18\x01 \x03(\v2\x16.poker.v1.PlayerConfigR\aplayers\x12\x1f\n" +
	"\vsmall_blind\x18\x02 \x01(\x04R\n" +
	"smallBlind\x12\x1b\n" +
	"\tbig_blind\x18\x03 \x01(\x04R\bbigBlind\x12'\n" +
	"\x0fdealer_position\x18\x04 \x01(\rR\x0edealerPosition\"e\n" +
	"\tHandState\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.poker.v1.GameStateBlobR\x05state\x12)\n" +
	"\x05views\x18\x02 \x03(\v2\x13.poker.v1.TableViewR\x05views\"\x81\x01\n" +
	"\x12ApplyActionRequest\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.poker.v1.GameStateBlobR\x05state\x12\x12\n" +
	"\x04seat\x18\x02 \x01(\rR\x04seat\x12(\n" +
	"\x06action\x18\x03 \x01(\v2\x10.poker.v1.ActionR\x06action\"\xb8\x01\n" +
	"\x11ApplyActionResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x05state\x18\x03 \x01(\v2\x17.poker.v1.GameStateBlobR\x05state\x12)\n" +
	"\x05views\x18\x04 \x03(\v2\x13.poker.v1.TableViewR\x05views\x12#\n" +
	"\rhand_complete\x18\x05 \x01(\bR\fhandComplete\"D\n" +
	"\x13ValidActionsRequest\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.poker.v1.GameStateBlobR\x05state\"N\n" +
	"\fValidActions\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\rR\x04seat\x12*\n" +
	"\aactions\x18\x02 \x03(\v2\x10.poker.v1.ActionR\aactions\"D\n" +
	"\x13CompleteHandRequest\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.poker.v1.GameStateBlobR\x05state\"5\n" +
	"\aWinning\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\rR\x04seat\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"\x9d\x01\n" +
	"\x12CompleteHandResult\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.poker.v1.GameStateBlobR\x05state\x12-\n" +
	"\bwinnings\x18\x02 \x03(\v2\x11.poker.v1.WinningR\bwinnings\x12)\n" +
	"\x05views\x18\x03 \x03(\v2\x13.poker.v1.TableViewR\x05views*\xb0\x01\n" +
	"\n" +
	"ActionKind\x12\x1b\n" +
	"\x17ACTION_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTION_KIND_FOLD\x10\x01\x12\x15\n" +
	"\x11ACTION_KIND_CHECK\x10\x02\x12\x14\n" +
	"\x10ACTION_KIND_CALL\x10\x03\x12\x13\n" +
	"\x0fACTION_KIND_BET\x10\x04\x12\x15\n" +
	"\x11ACTION_KIND_RAISE\x10\x05\x12\x16\n" +
	"\x12ACTION_KIND_ALL_IN\x10\x06*a\n" +
	"\x04Suit\x12\x14\n" +
	"\x10SUIT_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SUIT_CLUBS\x10\x01\x12\x11\n" +
	"\rSUIT_DIAMONDS\x10\x02\x12\x0f\n" +
	"\vSUIT_HEARTS\x10\x03\x12\x0f\n" +
	"\vSUIT_SPADES\x10\x04*\xdf\x01\n" +
	"\x04Rank\x12\x14\n" +
	"\x10RANK_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bRANK_TWO\x10\x02\x12\x0e\n" +
	"\n" +
	"RANK_THREE\x10\x03\x12\r\n" +
	"\tRANK_FOUR\x10\x04\x12\r\n" +
	"\tRANK_FIVE\x10\x05\x12\f\n" +
	"\bRANK_SIX\x10\x06\x12\x0e\n" +
	"\n" +
	"RANK_SEVEN\x10\a\x12\x0e\n" +
	"\n" +
	"RANK_EIGHT\x10\b\x12\r\n" +
	"\tRANK_NINE\x10\t\x12\f\n" +
	"\bRANK_TEN\x10\n" +
	"\x12\r\n" +
	"\tRANK_JACK\x10\v\x12\x0e\n" +
	"\n" +
	"RANK_QUEEN\x10\f\x12\r\n" +
	"\tRANK_KING\x10\r\x12\f\n" +
	"\bRANK_ACE\x10\x0e*w\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePHASE_PRE_FLOP\x10\x01\x12\x0e\n" +
	"\n" +
	"PHASE_FLOP\x10\x02\x12\x0e\n" +
	"\n" +
	"PHASE_TURN\x10\x03\x12\x0f\n" +
	"\vPHASE_RIVER\x10\x04\x12\x12\n" +
	"\x0ePHASE_SHOWDOWN\x10\x052\xaa\x02\n" +
	"\rEngineService\x128\n" +
	"\aNewHand\x12\x18.poker.v1.NewHandRequest\x1a\x13.poker.v1.HandState\x12H\n" +
	"\vApplyAction\x12\x1c.poker.v1.ApplyActionRequest\x1a\x1b.poker.v1.ApplyActionResult\x12H\n" +
	"\x0fGetValidActions\x12\x1d.poker.v1.ValidActionsRequest\x1a\x16.poker.v1.ValidActions\x12K\n" +
	"\fCompleteHand\x12\x1d.poker.v1.CompleteHandRequest\x1a\x1c.poker.v1.CompleteHandResultBEZCgithub.com/JShand18/ssh-poker-game/gateway/internal/pokerpb;pokerpbb\x06proto3"

var (
	file_poker_proto_rawDescOnce sync.Once
	file_poker_proto_rawDescData []byte
)

func file_poker_proto_rawDescGZIP() []byte {
	file_poker_proto_rawDescOnce.Do(func() {
		file_poker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poker_proto_rawDesc), len(file_poker_proto_rawDesc)))
	})
	return file_poker_proto_rawDescData
}

var file_poker_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_poker_proto_goTypes = []any{
	(ActionKind)(0),             // 0: poker.v1.ActionKind
	(Suit)(0),                   // 1: poker.v1.Suit
	(Rank)(0),                   // 2: poker.v1.Rank
	(Phase)(0),                  // 3: poker.v1.Phase
	(*GameStateBlob)(nil),       // 4: poker.v1.GameStateBlob
	(*Action)(nil),              // 5: poker.v1.Action
	(*Card)(nil),                // 6: poker.v1.Card
	(*SeatView)(nil),            // 7: poker.v1.SeatView
	(*TableView)(nil),           // 8: poker.v1.TableView
	(*PlayerConfig)(nil),        // 9: poker.v1.PlayerConfig
	(*NewHandRequest)(nil),      // 10: poker.v1.NewHandRequest
	(*HandState)(nil),           // 11: poker.v1.HandState
	(*ApplyActionRequest)(nil),  // 12: poker.v1.ApplyActionRequest
	(*ApplyActionResult)(nil),   // 13: poker.v1.ApplyActionResult
	(*ValidActionsRequest)(nil), // 14: poker.v1.ValidActionsRequest
	(*ValidActions)(nil),        // 15: poker.v1.ValidActions
	(*CompleteHandRequest)(nil), // 16: poker.v1.CompleteHandRequest
	(*Winning)(nil),             // 17: poker.v1.Winning
	(*CompleteHandResult)(nil),  // 18: poker.v1.CompleteHandResult
}
var file_poker_proto_depIdxs = []int32{
	0,  // 0: poker.v1.Action.kind:type_name -> poker.v1.ActionKind
	2,  // 1: poker.v1.Card.rank:type_name -> poker.v1.Rank
	1,  // 2: poker.v1.Card.suit:type_name -> poker.v1.Suit
	6,  // 3: poker.v1.SeatView.hole_cards:type_name -> poker.v1.Card
	3,  // 4: poker.v1.TableView.phase:type_name -> poker.v1.Phase
	6,  // 5: poker.v1.TableView.community_cards:type_name -> poker.v1.Card
	7,  // 6: poker.v1.TableView.seats:type_name -> poker.v1.SeatView
	9,  // 7: poker.v1.NewHandRequest.players:type_name -> poker.v1.PlayerConfig
	4,  // 8: poker.v1.HandState.state:type_name -> poker.v1.GameStateBlob
	8,  // 9: poker.v1.HandState.views:type_name -> poker.v1.TableView
	4,  // 10: poker.v1.ApplyActionRequest.state:type_name -> poker.v1.GameStateBlob
	5,  // 11: poker.v1.ApplyActionRequest.action:type_name -> poker.v1.Action
	4,  // 12: poker.v1.ApplyActionResult.state:type_name -> poker.v1.GameStateBlob
	8,  // 13: poker.v1.ApplyActionResult.views:type_name -> poker.v1.TableView
	4,  // 14: poker.v1.ValidActionsRequest.state:type_name -> poker.v1.GameStateBlob
	5,  // 15: poker.v1.ValidActions.actions:type_name -> poker.v1.Action
	4,  // 16: poker.v1.CompleteHandRequest.state:type_name -> poker.v1.GameStateBlob
	4,  // 17: poker.v1.CompleteHandResult.state:type_name -> poker.v1.GameStateBlob
	17, // 18: poker.v1.CompleteHandResult.winnings:type_name -> poker.v1.Winning
	8,  // 19: poker.v1.CompleteHandResult.views:type_name -> poker.v1.TableView
	10, // 20: poker.v1.EngineService.NewHand:input_type -> poker.v1.NewHandRequest
	12, // 21: poker.v1.EngineService.ApplyAction:input_type -> poker.v1.ApplyActionRequest
	14, // 22: poker.v1.EngineService.GetValidActions:input_type -> poker.v1.ValidActionsRequest
	16, // 23: poker.v1.EngineService.CompleteHand:input_type -> poker.v1.CompleteHandRequest
	11, // 24: poker.v1.EngineService.NewHand:output_type -> poker.v1.HandState
	13, // 25: poker.v1.EngineService.ApplyAction:output_type -> poker.v1.ApplyActionResult
	15, // 26: poker.v1.EngineService.GetValidActions:output_type -> poker.v1.ValidActions
	18, // 27: poker.v1.EngineService.CompleteHand:output_type -> poker.v1.CompleteHandResult
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_poker_proto_init() }
func file_poker_proto_init() {
	if File_poker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poker_proto_rawDesc), len(file_poker_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poker_proto_goTypes,
		DependencyIndexes: file_poker_proto_depIdxs,
		EnumInfos:         file_poker_proto_enumTypes,
		MessageInfos:      file_poker_proto_msgTypes,
	}.Build()
	File_poker_proto = out.File
	file_poker_proto_goTypes = nil
	file_poker_proto_depIdxs = nil
}
