// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: poker.proto

package pokerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_NewHand_FullMethodName         = "/poker.v1.EngineService/NewHand"
	EngineService_ApplyAction_FullMethodName     = "/poker.v1.EngineService/ApplyAction"
	EngineService_GetValidActions_FullMethodName = "/poker.v1.EngineService/GetValidActions"
	EngineService_CompleteHand_FullMethodName    = "/poker.v1.EngineService/CompleteHand"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineService is a stateless rules engine: every call takes the current
// state (or hand config) and returns the next state plus rendered views.
type EngineServiceClient interface {
	NewHand(ctx context.Context, in *NewHandRequest, opts ...grpc.CallOption) (*HandState, error)
	ApplyAction(ctx context.Context, in *ApplyActionRequest, opts ...grpc.CallOption) (*ApplyActionResult, error)
	GetValidActions(ctx context.Context, in *ValidActionsRequest, opts ...grpc.CallOption) (*ValidActions, error)
	CompleteHand(ctx context.Context, in *CompleteHandRequest, opts ...grpc.CallOption) (*CompleteHandResult, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) NewHand(ctx context.Context, in *NewHandRequest, opts ...grpc.CallOption) (*HandState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandState)
	err := c.cc.Invoke(ctx, EngineService_NewHand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ApplyAction(ctx context.Context, in *ApplyActionRequest, opts ...grpc.CallOption) (*ApplyActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyActionResult)
	err := c.cc.Invoke(ctx, EngineService_ApplyAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetValidActions(ctx context.Context, in *ValidActionsRequest, opts ...grpc.CallOption) (*ValidActions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidActions)
	err := c.cc.Invoke(ctx, EngineService_GetValidActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) CompleteHand(ctx context.Context, in *CompleteHandRequest, opts ...grpc.CallOption) (*CompleteHandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteHandResult)
	err := c.cc.Invoke(ctx, EngineService_CompleteHand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
//
// EngineService is a stateless rules engine: every call takes the current
// state (or hand config) and returns the next state plus rendered views.
type EngineServiceServer interface {
	NewHand(context.Context, *NewHandRequest) (*HandState, error)
	ApplyAction(context.Context, *ApplyActionRequest) (*ApplyActionResult, error)
	GetValidActions(context.Context, *ValidActionsRequest) (*ValidActions, error)
	CompleteHand(context.Context, *CompleteHandRequest) (*CompleteHandResult, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) NewHand(context.Context, *NewHandRequest) (*HandState, error) {
	return nil, status.Error(codes.Unimplemented, "method NewHand not implemented")
}
func (UnimplementedEngineServiceServer) ApplyAction(context.Context, *ApplyActionRequest) (*ApplyActionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyAction not implemented")
}
func (UnimplementedEngineServiceServer) GetValidActions(context.Context, *ValidActionsRequest) (*ValidActions, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValidActions not implemented")
}
func (UnimplementedEngineServiceServer) CompleteHand(context.Context, *CompleteHandRequest) (*CompleteHandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteHand not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_NewHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewHandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).NewHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_NewHand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).NewHand(ctx, req.(*NewHandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ApplyAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ApplyAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ApplyAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ApplyAction(ctx, req.(*ApplyActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetValidActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetValidActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetValidActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetValidActions(ctx, req.(*ValidActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_CompleteHand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteHandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CompleteHand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CompleteHand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CompleteHand(ctx, req.(*CompleteHandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poker.v1.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewHand",
			Handler:    _EngineService_NewHand_Handler,
		},
		{
			MethodName: "ApplyAction",
			Handler:    _EngineService_ApplyAction_Handler,
		},
		{
			MethodName: "GetValidActions",
			Handler:    _EngineService_GetValidActions_Handler,
		},
		{
			MethodName: "CompleteHand",
			Handler:    _EngineService_CompleteHand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poker.proto",
}
